#!/bin/bash
jupyter labextension install jupyterlab_iframe/js
jupyter lab build --dev-build=False --minimize=False
jupyter serverextension enable --py jupyterlab_iframe


config="c.JupyterLabIFrame.welcome = 'local://binder/landing.html'"

mkdir -p ~/.jupyter
echo -e $config > ~/.jupyter/jupyter_notebook_config.py


